from flaskapp.extensions import db

from .base import Base


class Book(Base):
    r"""
    ORM class representing book

    Parameters
    ----------
    isbn : str
         Number identifies a specific book.
    title : str
        Book title.
    author : str
        Author of the book
    date_of_publication : datetime
         Date of publication
    created : datetime
        Generated by postgres.
    last_modified : datetime
        Generated by postgres.
    """

    __tablename__ = "book"

    isbn = db.Column(db.String(16), primary_key=True, nullable=False)
    title = db.Column(db.String(128))
    author = db.Column(db.String(128))
    date_of_publication = db.Column(db.DateTime)
    created = db.Column(db.DateTime, server_default=db.func.now())
    last_modified = db.Column(db.DateTime, server_default=db.func.now(), onupdate=db.func.current_timestamp())
